version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: piutang_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: piutang_user
      POSTGRES_PASSWORD: piutang_password
      POSTGRES_DB: piutang_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U piutang_user -d piutang_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piutang_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://piutang_user:piutang_password@postgres:5432/piutang_db?schema=public
      - NEXTAUTH_SECRET=your-secret-key-here-change-in-production
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data: